version: '3.8'

services:
  php:
    build: ./docker/php
    container_name: yii2_php
    volumes:
    - ./:/app
    working_dir: /app
    depends_on:
    - postgres
    - redis
    networks:
    - yii2net

  nginx:
    image: nginx:alpine
    container_name: yii2_nginx
    ports:
    - "8080:80"
    volumes:
    - ./:/app
    - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    - php
    networks:
    - yii2net

  postgres:
    image: postgres:14
    container_name: yii2_postgres
    environment:
      POSTGRES_DB: family
      POSTGRES_USER: yii2
      POSTGRES_PASSWORD: secret
    ports:
    - "5433:5432"
    volumes:
    - postgres_data:/var/lib/postgresql/data
    networks:
    - yii2net

  redis:
    image: redis:alpine
    container_name: yii2_redis
    networks:
    - yii2net

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: yii2_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
    - "5050:80"
    depends_on:
    - postgres
    volumes:
    - pgadmin_data:/var/lib/pgadmin
    networks:
    - yii2net

volumes:
  postgres_data:
  pgadmin_data:

networks:
  yii2net:
